# .streamlit/config.toml
[theme]
base = "dark"
primaryColor = "#F7D917" # Cor prim√°ria
backgroundColor = "#0F172A" # Fundo escuro absoluto (Estilo Tailwind Slate-900)
secondaryBackgroundColor = "#1E293B" # Fundo do menu lateral (Slate-800)
textColor = "#F8FAFC"
font = "sans serif"